import operator
from typing import Annotated, Dict, List, Literal, Optional

from pydantic import BaseModel, Field
from typing_extensions import TypedDict


class Evidence(BaseModel):
    """Evidence collected by forensic detectives."""
    
    goal: str = Field(description="The forensic goal being investigated")
    found: bool = Field(description="Whether the artifact exists")
    content: Optional[str] = Field(default=None, description="Content of the evidence found")
    location: str = Field(
        description="File path, commit hash, or document section where evidence was found"
    )
    rationale: str = Field(
        description="Rationale for the confidence level on this evidence"
    )
    confidence: float = Field(ge=0.0, le=1.0, description="Confidence level from 0.0 to 1.0")


class JudicialOpinion(BaseModel):
    """Opinion rendered by a judge persona."""
    
    judge: Literal["Prosecutor", "Defense", "TechLead"] = Field(
        description="Which judge rendered this opinion"
    )
    criterion_id: str = Field(description="The rubric criterion ID being evaluated")
    score: int = Field(ge=1, le=5, description="Score from 1 to 5")
    argument: str = Field(description="Argument supporting the score")
    cited_evidence: List[str] = Field(
        description="List of evidence IDs cited to support the argument"
    )


class CriterionResult(BaseModel):
    """Final result for a single rubric criterion."""
    
    dimension_id: str = Field(description="ID of the rubric dimension")
    dimension_name: str = Field(description="Name of the rubric dimension")
    final_score: int = Field(ge=1, le=5, description="Final aggregated score from 1 to 5")
    judge_opinions: List[JudicialOpinion] = Field(
        description="All three judge opinions for this criterion"
    )
    dissent_summary: Optional[str] = Field(
        default=None,
        description="Summary of disagreements when score variance > 2"
    )
    remediation: str = Field(
        description="Specific file-level instructions for improvement"
    )


class AuditReport(BaseModel):
    """Final audit report generated by Chief Justice."""
    
    repo_url: str = Field(description="Repository URL that was audited")
    executive_summary: str = Field(
        description="High-level summary of findings and overall score"
    )
    overall_score: float = Field(
        ge=1.0, le=5.0, description="Overall aggregated score from 1.0 to 5.0"
    )
    criteria: List[CriterionResult] = Field(
        description="Detailed results for each rubric criterion"
    )
    remediation_plan: str = Field(
        description="Comprehensive remediation plan with actionable steps"
    )


class AgentState(TypedDict):
    """State management for the LangGraph workflow."""
    
    repo_url: str
    pdf_path: str
    rubric_dimensions: List[Dict]
    
    # Parallel detectives write to this dict, use reducer to prevent overwrites
    evidences: Annotated[
        Dict[str, List[Evidence]], operator.ior
    ]
    
    # Judges append to this list
    opinions: Annotated[
        List[JudicialOpinion], operator.add
    ]
    
    final_report: Optional[AuditReport]
    
    # Error handling
    error: Optional[str]
    error_context: Optional[str]